<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match_service.proto

namespace Google\Cloud\Aiplatform\Container\V1beta1\BatchMatchResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Batched responses for one index.
 *
 * Generated from protobuf message <code>google.cloud.aiplatform.container.v1beta1.BatchMatchResponse.BatchMatchResponsePerIndex</code>
 */
class BatchMatchResponsePerIndex extends \Google\Protobuf\Internal\Message
{
    /**
     * The ID of the DeployedIndex that produced the responses.
     *
     * Generated from protobuf field <code>string deployed_index_id = 1;</code>
     */
    protected $deployed_index_id = '';
    /**
     * The match responses produced by the index identified by the above
     * deployed_index_id. This field is set only when the query against that
     * index succeed.
     *
     * Generated from protobuf field <code>repeated .google.cloud.aiplatform.container.v1beta1.MatchResponse responses = 2;</code>
     */
    private $responses;
    /**
     * The status of response for the batch query identified by the above
     * deployed_index_id.
     *
     * Generated from protobuf field <code>.google.rpc.Status status = 3;</code>
     */
    protected $status = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $deployed_index_id
     *           The ID of the DeployedIndex that produced the responses.
     *     @type array<\Google\Cloud\Aiplatform\Container\V1beta1\MatchResponse>|\Google\Protobuf\Internal\RepeatedField $responses
     *           The match responses produced by the index identified by the above
     *           deployed_index_id. This field is set only when the query against that
     *           index succeed.
     *     @type \Google\Rpc\Status $status
     *           The status of response for the batch query identified by the above
     *           deployed_index_id.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MatchService::initOnce();
        parent::__construct($data);
    }

    /**
     * The ID of the DeployedIndex that produced the responses.
     *
     * Generated from protobuf field <code>string deployed_index_id = 1;</code>
     * @return string
     */
    public function getDeployedIndexId()
    {
        return $this->deployed_index_id;
    }

    /**
     * The ID of the DeployedIndex that produced the responses.
     *
     * Generated from protobuf field <code>string deployed_index_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDeployedIndexId($var)
    {
        GPBUtil::checkString($var, True);
        $this->deployed_index_id = $var;

        return $this;
    }

    /**
     * The match responses produced by the index identified by the above
     * deployed_index_id. This field is set only when the query against that
     * index succeed.
     *
     * Generated from protobuf field <code>repeated .google.cloud.aiplatform.container.v1beta1.MatchResponse responses = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResponses()
    {
        return $this->responses;
    }

    /**
     * The match responses produced by the index identified by the above
     * deployed_index_id. This field is set only when the query against that
     * index succeed.
     *
     * Generated from protobuf field <code>repeated .google.cloud.aiplatform.container.v1beta1.MatchResponse responses = 2;</code>
     * @param array<\Google\Cloud\Aiplatform\Container\V1beta1\MatchResponse>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResponses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Aiplatform\Container\V1beta1\MatchResponse::class);
        $this->responses = $arr;

        return $this;
    }

    /**
     * The status of response for the batch query identified by the above
     * deployed_index_id.
     *
     * Generated from protobuf field <code>.google.rpc.Status status = 3;</code>
     * @return \Google\Rpc\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * The status of response for the batch query identified by the above
     * deployed_index_id.
     *
     * Generated from protobuf field <code>.google.rpc.Status status = 3;</code>
     * @param \Google\Rpc\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Google\Rpc\Status::class);
        $this->status = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(BatchMatchResponsePerIndex::class, \Google\Cloud\Aiplatform\Container\V1beta1\BatchMatchResponse_BatchMatchResponsePerIndex::class);

