<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match_service.proto

namespace Google\Cloud\Aiplatform\Container\V1beta1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Aiplatform\Container\V1beta1\BatchMatchResponse\BatchMatchResponsePerIndex instead.
     * @deprecated
     */
    class BatchMatchResponse_BatchMatchResponsePerIndex {}
}
class_exists(BatchMatchResponse\BatchMatchResponsePerIndex::class);
@trigger_error('Google\Cloud\Aiplatform\Container\V1beta1\BatchMatchResponse_BatchMatchResponsePerIndex is deprecated and will be removed in the next major release. Use Google\Cloud\Aiplatform\Container\V1beta1\BatchMatchResponse\BatchMatchResponsePerIndex instead', E_USER_DEPRECATED);

