<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match_service.proto

namespace Google\Cloud\Aiplatform\Container\V1beta1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Aiplatform\Container\V1beta1\BatchMatchRequest\BatchMatchRequestPerIndex instead.
     * @deprecated
     */
    class BatchMatchRequest_BatchMatchRequestPerIndex {}
}
class_exists(BatchMatchRequest\BatchMatchRequestPerIndex::class);
@trigger_error('Google\Cloud\Aiplatform\Container\V1beta1\BatchMatchRequest_BatchMatchRequestPerIndex is deprecated and will be removed in the next major release. Use Google\Cloud\Aiplatform\Container\V1beta1\BatchMatchRequest\BatchMatchRequestPerIndex instead', E_USER_DEPRECATED);

