<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match_service.proto

namespace Google\Cloud\Aiplatform\Container\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response of a match query.
 *
 * Generated from protobuf message <code>google.cloud.aiplatform.container.v1beta1.MatchResponse</code>
 */
class MatchResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * All its neighbors.
     *
     * Generated from protobuf field <code>repeated .google.cloud.aiplatform.container.v1beta1.MatchResponse.Neighbor neighbor = 1;</code>
     */
    private $neighbor;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Google\Cloud\Aiplatform\Container\V1beta1\MatchResponse\Neighbor>|\Google\Protobuf\Internal\RepeatedField $neighbor
     *           All its neighbors.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MatchService::initOnce();
        parent::__construct($data);
    }

    /**
     * All its neighbors.
     *
     * Generated from protobuf field <code>repeated .google.cloud.aiplatform.container.v1beta1.MatchResponse.Neighbor neighbor = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNeighbor()
    {
        return $this->neighbor;
    }

    /**
     * All its neighbors.
     *
     * Generated from protobuf field <code>repeated .google.cloud.aiplatform.container.v1beta1.MatchResponse.Neighbor neighbor = 1;</code>
     * @param array<\Google\Cloud\Aiplatform\Container\V1beta1\MatchResponse\Neighbor>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNeighbor($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Aiplatform\Container\V1beta1\MatchResponse\Neighbor::class);
        $this->neighbor = $arr;

        return $this;
    }

}

