<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match_service.proto

namespace Google\Cloud\Aiplatform\Container\V1beta1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Aiplatform\Container\V1beta1\MatchResponse\Neighbor instead.
     * @deprecated
     */
    class MatchResponse_Neighbor {}
}
class_exists(MatchResponse\Neighbor::class);
@trigger_error('Google\Cloud\Aiplatform\Container\V1beta1\MatchResponse_Neighbor is deprecated and will be removed in the next major release. Use Google\Cloud\Aiplatform\Container\V1beta1\MatchResponse\Neighbor instead', E_USER_DEPRECATED);

